name: Update RaiPlaySound Feeds
on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:
jobs:
  update-feeds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml feedendum chardet python-dateutil certifi
      - name: Generate Feeds
        run: python scripts/generate_feeds.py
      - name: Debug - Verifica file generati
        run: |
          echo "Contenuto della directory:"
          ls -l
          echo "Contenuto dei feed XML:"
          for file in feed_*.xml; do
            echo "Contenuto di $file:"
            cat "$file"
            echo "-----------------------------"
          done
      - name: Verifica dimensione file XML
        run: |
          for file in feed_*.xml; do
            size=$(wc -c < "$file")
            if [ "$size" -lt 50 ]; then
              echo "Il file $file è troppo piccolo, potrebbe essere vuoto!"
            fi
          done
      - name: Commit and Push (con autenticazione)
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/t0m0n/raiplay-feed.git
          git add feed_*.xml || true
          git diff --staged --quiet || (git commit -m "Aggiornamento automatico dei feeds" && git push origin main)
